<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Aberdeen CityAberdeenshireAdurAllerd_47c19d</name>
   <tag></tag>
   <elementGuidId>a3ce3036-32e3-4b43-9b60-72de33f2b9b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='authorities']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#authorities</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authorities</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorities</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aberdeen CityAberdeenshireAdurAllerdaleAmber ValleyAngleseyAngusAntrim and NewtownabbeyArds and North DownArgyll and ButeArmagh City, Banbridge and CraigavonArunAshfieldAshfordBaberghBarking and DagenhamBarnetBarnsleyBarrow-in-FurnessBasildonBasingstoke and DeaneBassetlawBath and North East SomersetBedfordBelfast CityBexleyBirminghamBlabyBlackburnBlackpoolBlaenau GwentBolsoverBoltonBostonBournemouth, Christchurch and PooleBracknell ForestBradfordBraintreeBrecklandBrentBrentwoodBridgendBrighton and HoveBristolBroadlandBromleyBromsgroveBroxbourneBroxtoweBuckinghamshireBurnleyBuryCaerphillyCalderdaleCambridge CityCamdenCannock ChaseCanterbury CityCardiffCarlisle CityCarmarthenshireCastle PointCauseway Coast and GlensCentral BedfordshireCeredigionCharnwoodChelmsfordCheltenhamCherwellCheshire EastCheshire West and ChesterChesterfieldChichesterChorleyCity of London CorporationClackmannanshireColchesterComhairle nan Eilean Siar (Western Isles)ConwyCopelandCornwallCotswoldCoventryCravenCrawleyCroydonDacorumDarlingtonDartfordDenbighshireDerby CityDerbyshire DalesDerry City and StrabaneDoncasterDorsetDoverDudleyDumfries and GallowayDundee CityDurhamEalingEast AyrshireEast CambridgeshireEast DevonEast DunbartonshireEast HampshireEast HertfordshireEast LindseyEast LothianEast RenfrewshireEast Riding of YorkshireEast StaffordshireEast SuffolkEastbourneEastleighEdenEdinburgh (City of)ElmbridgeEnfieldEpping ForestEpsom and EwellErewashExeter CityFalkirkFarehamFenlandFermanagh and OmaghFifeFlintshireFolkestone and HytheForest of DeanFyldeGatesheadGedlingGlasgow CityGloucester CityGosportGraveshamGreat YarmouthGreenwichGuildfordGwyneddHackneyHaltonHambletonHammersmith and FulhamHarboroughHaringeyHarlowHarrogateHarrowHartHartlepoolHastingsHavantHaveringHerefordshireHertsmereHigh PeakHighlandHillingdonHinckley and BosworthHorshamHounslowHull and Goole PortHull CityHuntingdonshireHyndburnInverclydeIpswichIsle of WightIsles of ScillyIslingtonKensington and ChelseaKing's Lynn and West NorfolkKingston-Upon-ThamesKirkleesKnowsleyLambethLancaster CityLeedsLeicester CityLewesLewishamLichfieldLincoln CityLisburn and Castlereagh CityLiverpoolLutonMaidstoneMaldonMalvern HillsManchesterMansfieldMedwayMeltonMendipMerthyr TydfilMertonMid and East AntrimMid DevonMid SuffolkMid SussexMid UlsterMiddlesbroughMidlothianMilton KeynesMole ValleyMonmouthshireMorayNeath Port TalbotNew ForestNewark and SherwoodNewcastle Upon TyneNewcastle-Under-LymeNewhamNewportNewry, Mourne and DownNorth AyrshireNorth DevonNorth East DerbyshireNorth East LincolnshireNorth HertfordshireNorth KestevenNorth LanarkshireNorth LincolnshireNorth NorfolkNorth NorthamptonshireNorth SomersetNorth TynesideNorth WarwickshireNorth West LeicestershireNorthumberlandNorwich CityNottingham CityNuneaton and BedworthOadby and WigstonOldhamOrkney IslandsOxford CityPembrokeshirePendlePerth and KinrossPeterborough CityPlymouth CityPortsmouthPowysPrestonReadingRedbridgeRedcar and ClevelandRedditchReigate and BansteadRenfrewshireRhondda Cynon TafRibble ValleyRichmondshireRichmond-Upon-ThamesRiver TeesRochdaleRochfordRossendaleRotherRotherhamRugbyRunnymedeRushcliffeRushmoorRutlandRyedaleSalfordSandwellScarboroughScottish BordersSedgemoorSeftonSelbySevenoaksSheffieldShetland IslandsShropshireSloughSolihullSomerset West and TauntonSouth AyrshireSouth CambridgeshireSouth DerbyshireSouth GloucestershireSouth HamsSouth HollandSouth KestevenSouth LakelandSouth LanarkshireSouth NorfolkSouth OxfordshireSouth RibbleSouth SomersetSouth StaffordshireSouth TynesideSouthamptonSouthend-On-SeaSouthwarkSpelthorneSt Albans CitySt HelensStaffordStaffordshire MoorlandsStevenageStirlingStockportStockton On TeesStoke-On-TrentStratford-on-AvonStroudSunderlandSurrey HeathSuttonSwaleSwanseaSwindonTamesideTamworthTandridgeTeignbridgeTelford and Wrekin CouncilTendringTest ValleyTewkesburyThanetThree RiversThurrockTonbridge and MallingTorbayTorfaenTorridgeTower HamletsTraffordTunbridge WellsUttlesfordVale of GlamorganVale of White HorseWakefieldWalsallWaltham ForestWandsworthWarringtonWarwickWatfordWaverleyWealdenWelwyn HatfieldWest BerkshireWest DevonWest DunbartonshireWest LancashireWest LindseyWest LothianWest NorthamptonshireWest OxfordshireWest SuffolkWestminsterWiganWiltshireWinchester CityWindsor and MaidenheadWirralWokingWokinghamWolverhamptonWorcester CityWorthingWrexhamWychavonWyreWyre ForestYork</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorities&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='authorities']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/aside/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose an Authority:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Page'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a Country:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Filter'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
